# Generated by Django 2.2.3 on 2019-08-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_ordereditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
