# Generated by Django 2.2.3 on 2019-08-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190812_1954'),
        ('cart', '0009_auto_20190812_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
