# Generated by Django 2.2.3 on 2019-08-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190812_1954'),
        ('cart', '0010_auto_20190812_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='products.Product', verbose_name='Товар'),
        ),
    ]
