# Generated by Django 2.2.3 on 2019-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190716_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='visible',
            field=models.CharField(choices=[('d-none', 'invisible'), ('', 'visible')], default='visible', max_length=15),
        ),
    ]
