# Generated by Django 2.2.3 on 2019-07-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190716_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.Category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='visible',
            field=models.CharField(choices=[('d-none', 'invisible'), (' ', 'visible')], default='visible', max_length=15, verbose_name='Видимость'),
        ),
    ]
