# Generated by Django 2.2.3 on 2019-07-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190721_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_date',
            new_name='timestamp',
        ),
    ]
