# Generated by Django 2.2.3 on 2019-07-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190730_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_page',
            field=models.BooleanField(default=False),
        ),
    ]
