# Generated by Django 2.2.3 on 2019-08-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_blog_main_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Редактирование статей на главной странице и привязывание к ним товаров, которые должны отображаться после нее.', 'verbose_name_plural': 'Редактирование статей на главной странице и привязывание к ним товаров, которые должны отображаться после нее.'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Редактирование разделов', 'verbose_name_plural': 'Редактирование разделов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Редактирование товаров', 'verbose_name_plural': 'Редактирование товаров'},
        ),
    ]
