# Generated by Django 2.2.3 on 2019-08-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190812_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Редактирование статей на главной странице.', 'verbose_name_plural': 'Редактирование статей на главной странице.'},
        ),
    ]
